name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate
          pip install requests

      - name: Run openai.py script
        run: |
          source myenv/bin/activate
          python openai.py
#tt
  list-and-download-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_TOKEN }}"

      - name: Create logs directory
        run: mkdir -p logs

      - name: List Available Runs
        id: list-runs
        run: |
          echo "Listing available runs for the repository..."
          gh run list --repo ${{ github.repository }} --limit 1 --json databaseId > logs/runs.json
          cat logs/runs.json
          RUN_ID=$(jq -r '.[0].databaseId' logs/runs.json)
          echo "Selected run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Wait for Run Completion
        run: |
          for i in {1..10}
          do
            STATUS=$(gh run view ${{ env.RUN_ID }} --json status --jq '.status')
            echo "Current run status: $STATUS"
            if [ "$STATUS" == "completed" ]; then
              echo "Run completed."
              break
            fi
            echo "Run not completed yet. Waiting..."
            sleep 30
          done
          if [ "$STATUS" != "completed" ]; then
            echo "Run did not complete in time."
            exit 1
          fi

      - name: Download Logs
        run: |
          mkdir -p logs
          echo "Downloading logs from GitHub API using run ID ${{ env.RUN_ID }}"
          gh run view ${{ env.RUN_ID }} --log > logs/logs.log
          if [ $? -ne 0 ]; then
            echo "Failed to download logs"
            cat logs/logs.log
            exit 1
          fi
          echo "Logs downloaded."
          cat logs/logs.log

      - name: Upload logs
        uses: actions/upload-artifact@v2
        with:
          name: workflow-logs
          path: logs/logs.log






  # logs-download:
  #   name: Download GH action logs
  #   runs-on: ubuntu-latest
  #   needs: run-script
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2.0.0

  #     - name: Download Logs
  #       run: |
  #         mkdir -p logs
  #         echo "Downloading logs from GitHub API"
  #         curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
  #              -H "Accept: application/vnd.github.v3+json" \
  #              -L -o logs/logs.json \
  #              https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/logs
  #         echo "Logs downloaded. Checking file type..."
  #         file logs/logs.json
  #         echo "Contents of logs.json:"
  #         cat logs/logs.json

  #     - name: Extract Logs from JSON
  #       run: |
  #         echo "Extracting log entries from JSON..."
  #         if jq -e . logs/logs.json > /dev/null 2>&1; then
  #           cat logs/logs.json | jq '.' > logs/extracted_logs.txt
  #           echo "Log entries extracted:"
  #           cat logs/extracted_logs.txt
  #         else
  #           echo "Downloaded JSON is not valid."
  #         fi

  #     - name: Upload logs
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: workflow-logs
  #         path: logs/







# name: CI Workflow

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# permissions:
#   actions: read
#   contents: read

# jobs:
#   run-script:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Python 3.12
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.12'

#     - name: Install dependencies
#       run: |
#         python -m venv myenv
#         source myenv/bin/activate
#         pip install requests

#     - name: Run openai.py script
#       run: |
#         source myenv/bin/activate
#         python openai.py

#   build-and-test:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Python 3.12
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.12'

#     - name: Install dependencies
#       run: |
#         python -m venv myenv
#         source myenv/bin/activate
#         pip install -r requirements.txt

#     # - name: Run tests
#     #   run: |
#     #     source myenv/bin/activate
#     #     pytest --maxfail=5 --disable-warnings



#   upload-logs:
#     runs-on: ubuntu-latest
#     needs: [run-script]

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Python 3.12
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.12'

#     - name: Install dependencies
#       run: |
#         python -m venv myenv
#         source myenv/bin/activate
#         pip install requests azure-storage-blob

#     - name: Upload logs to Azure
#       env:
#         GITHUB_TOKEN: ${{ secrets.PAT }}
#         GITHUB_RUN_ID: ${{ github.run_id }}
#         GITHUB_REPOSITORY: ${{ github.repository }}
#         AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
#       run: |
#         source myenv/bin/activate
#         python scripts/upload_logs_to_azure.py
#   # debug-fetch-logs:
#   #   runs-on: ubuntu-latest
#   #   needs: [run-script, build-and-test]

#   #   steps:
#   #   - name: Checkout repository
#   #     uses: actions/checkout@v2

#   #   - name: Set up Python 3.12
#   #     uses: actions/setup-python@v4
#   #     with:
#   #       python-version: '3.12'

#   #   - name: Install dependencies
#   #     run: |
#   #       python -m venv myenv
#   #       source myenv/bin/activate
#   #       pip install requests

#   #   - name: Debug Fetch Logs
#   #     env:
#   #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#   #       GITHUB_RUN_ID: ${{ github.run_id }}
#   #       GITHUB_REPOSITORY: ${{ github.repository }}
#   #     run: |
#   #       source myenv/bin/activate
#   #       python scripts/debug_fetch_logs.py
