name: Log Collection Workflow

on:
  workflow_run:
    workflows: ["Main CI Workflow"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  collect-logs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate
          pip install requests azure-storage-blob

      - name: Debug environment variables
        run: |
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
          echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
          echo "REPO_OWNER: ${{ github.repository_owner }}"
          echo "REPO_NAME: ${{ github.event.repository.name }}"

      - name: Upload logs to Azure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ github.run_id }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
        run: |
          source myenv/bin/activate
          python scripts/debug_fetch_logs.py
          
