name: Log Collection and Analysis Workflow

on:
  workflow_run:
    workflows: ["Main CI Workflow"]
    types:
      - completed

permissions:
  actions: read
  contents: read
  issues: write
  pull-requests: write

jobs:
  collect-logs:
    runs-on: ubuntu-latest

    outputs:
      analysis-summary: ${{ steps.generate-summary.outputs.summary }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv myenv
          source myenv/bin/activate
          pip install requests azure-storage-blob jq

      - name: List files in workspace (after checkout)
        run: ls -la

      - name: Verify run_id.txt content
        run: cat run_id.txt

      - name: Upload logs and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_DH_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          CUSTOM_SERVICE_COOKIE: ${{ secrets.CUSTOM_SERVICE_COOKIE }}
        run: |
          source myenv/bin/activate
          python scripts/debug_fetch_logs.py run_id.txt

      - name: List files after analysis
        run: ls -la scripts/

      - name: Generate analysis summary
        id: generate-summary
        run: |
          summary="## Analysis Summary\n"
          for file in ./scripts/*_analysis_*.txt; do
            if [ -f "$file" ]; then
              summary+="### Summary of $file\n"
              summary+=$(cat "$file")
              summary+="\n\n"
            else
              summary+="No analysis files found.\n"
            fi
          done
          echo "::set-output name=summary::$summary"

      - name: Display summary
        run: echo "${{ steps.generate-summary.outputs.summary }}"


      # - name: Check API rate limits
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_DH_TOKEN }}
      #   run: |
      #     rate_limit_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
      #     -H "Accept: application/vnd.github.v3+json" \
      #     https://api.github.com/rate_limit)
      #     echo "Rate Limit Response: $rate_limit_response"

      # - name: Verify token permissions
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_DH_TOKEN }}
      #   run: |
      #     curl -H "Authorization: token $GITHUB_TOKEN" \
      #          -H "Accept: application/vnd.github.v3+json" \
      #          https://api.github.com/user

      # - name: Check token value
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.FULL_ACCESS_DH_TOKEN }}
      #   run: echo $GITHUB_TOKEN







































# name: Log Collection and Analysis Workflow

# on:
#   workflow_run:
#     workflows: ["Main CI Workflow"]
#     types:
#       - completed

# permissions:
#   actions: read
#   contents: read

# jobs:
#   collect-logs:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Set up Python 3.12
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.12'

#       - name: Install dependencies
#         run: |
#           python -m venv myenv
#           source myenv/bin/activate
#           pip install requests azure-storage-blob

#       - name: List files in workspace (after checkout)
#         run: ls -la

#       - name: Verify run_id.txt content
#         run: cat run_id.txt

#       - name: Upload logs to Azure
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           GITHUB_REPOSITORY: ${{ github.repository }}
#           REPO_OWNER: ${{ github.repository_owner }}
#           REPO_NAME: ${{ github.event.repository.name }}
#           AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
#           CUSTOM_SERVICE_COOKIE: ${{ secrets.CUSTOM_SERVICE_COOKIE }}
#         run: |
#           source myenv/bin/activate
#           python scripts/debug_fetch_logs.py run_id.txt

#       - name: List all files after analysis
#         run: |
#           cd scripts
#           ls -la
