name: Run openai API connection Script

on:
  push:
    branches:
      - automation_logs
  pull_request:
    branches:
      - automation_logs

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m venv myenv
        source myenv/bin/activate
        pip install requests

    - name: Run openai.py script
      run: |
        source myenv/bin/activate
        python openai.py